import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e6f0fa',
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    paddingBottom: 50, // Espaço para o rodapé
  },
  header: {
    backgroundColor: '#e6f0fa',
    padding: 15,
    alignItems: 'center',
  },
  logo: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  logoImage: {
    width: '100%',
    resizeMode: 'contain',
  },
  logoText: {
    color: '#ff7f00',
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#003366',
    marginBottom: 20,
  },
  input: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '25%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  inputdd: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '15.8%',
    marginLeft: '25%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  inputdata: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '15.8%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  inputend: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '35%',
    marginLeft: '25%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  inputuf: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '15%',
    marginRight: '25%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  locationContainer: {
    flexDirection: 'row',
    width: '25%',
    marginBottom: 10,
  },
  locationInput: {
    flex: 1,
  },
  locationButton: {
    backgroundColor: '#003366',
    padding: 10,
    borderRadius: 8,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordContainer: {
    flexDirection: 'row',
    width: '25%',
    marginBottom: 10,
  },
  passwordInput: {
    flex: 1,
  },
  eyeButton: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eyeIcon: {
    fontSize: 20,
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  termsLabel: {
    marginLeft: 10,
    fontSize: 16,
    color: '#003366',
  },
  termsLink: {
    color: '#ff7f00',
    textDecorationLine: 'underline',
  },
  button: {
    backgroundColor: '#ff7f00',
    padding: 12,
    borderRadius: 8,
    width: '25%',
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
    fontSize: 12,
    color: '#003366',
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '50%',
    marginBottom: 10,
    gap: 8,
  },
  dateContainer: {
    flexDirection: 'row',
    width: '100%',
    gap: 8,
  },
  label: {
    fontSize: 16,
    color: '#003366',
  },
  errorText: {
    color: '#ff0000',
    fontSize: 12,
    marginTop: -5,
    marginBottom: 5,
    textAlign: 'center',
  },
});
