version: '3.8'

name: frontend-delbicos-prod

services:
  delbicos-frontend:
    image: ${DOCKERHUB_USERNAME}/delbicos-frontend:latest
    container_name: webapp-delbicos
    restart: always
    ports:
      - '80:80'
    environment:
      - EXPO_PUBLIC_ENVIRONMENT=production
      - EXPO_PUBLIC_DOMAIN_ANDROID=${EXPO_PUBLIC_DOMAIN_ANDROID}
      - EXPO_PUBLIC_DOMAIN_IOS=${EXPO_PUBLIC_DOMAIN_IOS}
      - EXPO_PUBLIC_PORT=${EXPO_PUBLIC_PORT}
      - EXPO_PUBLIC_HTTP_PROTOCOL=https
      - EXPO_PUBLIC_WS_PROTOCOL=wss
      - EXPO_PUBLIC_UNSPLASH_API_KEY=${EXPO_PUBLIC_UNSPLASH_API_KEY}
      - EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=${EXPO_PUBLIC_GOOGLE_MAPS_API_KEY}
      - EXPO_PUBLIC_LOCATIONIQ_API_KEY=${EXPO_PUBLIC_LOCATIONIQ_API_KEY}
      - EXPO_PUBLIC_GOOGLE_ANALYTICS_ID=${EXPO_PUBLIC_GOOGLE_ANALYTICS_ID}
      - EXPO_PUBLIC_CLARITY_ID=${EXPO_PUBLIC_CLARITY_ID}
    networks:
      - delbicos-network

networks:
  delbicos-network:
    external: true
    name: delbicos-shared-network