import colors from '@theme/colors';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.secondaryGray,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  topBar: { paddingVertical: 8, alignItems: 'center' },
  brand: { fontSize: 22, fontWeight: '800', color: colors.primaryBlue },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    marginTop: 6,
    marginBottom: 8,
  },
  sectionLeft: { fontSize: 18, fontWeight: '700', color: colors.primaryBlack },
  sectionRight: { fontSize: 18, fontWeight: '700', color: colors.primaryBlack },
  row: { alignItems: 'stretch', justifyContent: 'center' },
  leftCol: { flex: 1 },
  rightCol: { flex: 1 },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  catBtn: {
    backgroundColor: colors.secondaryBeige,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    margin: 6,
    minWidth: '29%',
    maxWidth: '42%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  catBtnActive: { backgroundColor: '#005A93' },
  catText: { color: colors.primaryOrange, fontWeight: '700' },
  catTextActive: { color: colors.primaryWhite },
  divider: { width: 2, backgroundColor: '#B8C3CF', marginHorizontal: 50 },
  calendarCard: {
    overflow: 'hidden',
    backgroundColor: colors.primaryOrange,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  cta: {
    backgroundColor: colors.primaryBlue,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 16,
    alignSelf: 'center',
    minWidth: 220,
  },
  ctaText: { color: colors.primaryWhite, fontSize: 16, fontWeight: '700' },
  footer: {
    textAlign: 'center',
    color: '#4C5A6B',
    marginTop: 20,
    marginBottom: 8,
    fontSize: 12,
  },
});
